config/routes.rb
Rails.application.routes.draw do
  get 'favorites/update'
  root to: 'lists#index'
  resources :lists, only: %i[index show new create] do
    get 'favorite', on: :collection
  end
  devise_for :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :list
end

app/models/list.rb
class List < ApplicationRecord
  enum status: { collective: 0, personal: 5 }

  belongs_to :user
  has_many :tasks, dependent: :destroy
  accepts_nested_attributes_for :tasks, allow_destroy: true

  validates :name, :status, presence: true
  
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :list

  validates :title, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :lists
  has_many :favorites
  has_many :tasks, through: :lists
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  def favorite_text
    @favorite_exists ? 'UnFavorite' : 'Favorite'
  end

  helper_method :favorite_text
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def update
    @favorite = Favorite.where(list: List.find(params[:list]), user: current_user)
    puts params
    if @favorite == []
      @favorite.create(list: List.find(params[:list]), user: current_user)
      @favorite_exists = true
    else
      @favorite.destroy_all
      @favorite_exists = false
    end
    respond_to do |format|
      format.html
      format.js
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
    @favorite_exists = Favorite.where(list: @list, user: current_user) != []
  end

  def favorite
    @lists = List.all
    @favorite_exists = Favorite.where(list: @list, user: current_user) != []
  end

  def show
    @list = List.find(params[:id])
    @favorite_exists = Favorite.where(list: @list, user: current_user) != []
  end

  def new
    @list = List.new
    @list.tasks.build
  end

  def create
    @list = List.new(list_params)
    @list.user = current_user
    if @list.save
      return redirect_to @list,
                         notice: 'Registrado com sucesso'
    end

    render :new
  end

  private

  def list_params
    params.require(:list).permit(:name, :description, :status, tasks_attributes: %i[id title])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def link_to_add_fields(name, f, association)
    new_object = f.object.send(association).klass.new

    id = new_object.object_id

    fields = f.fields_for(association, new_object, child_index: id) do |builder|
      render(association.to_s.singularize + '_fields', f: builder)
    end
    link_to(name, '#', class: 'add_fields', data: { id: id, fields: fields.gsub("\n", '') })
  end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/favorites/update.js.erb
$('#favorite_link').text("<%= favorite_text %>");

app/views/home/index.html.erb
<%= link_to 'Lista de Tarefas', lists_path %>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">

  <%= link_to "MiniAPP", root_path, class: "navbar-brand", id: "logo" %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav mr-auto">
      <% if current_user %>
        <li class="nav-item">
          <%= link_to "Detalhes da conta", edit_user_registration_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Todas as Listas', lists_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Listas Favoritas', favorite_lists_path, class: 'nav-link' %>
        </li>
    </ul>

    <span class="navbar-text">
        <%= link_to('Logout', destroy_user_session_path, class: 'btn  my-2 my-sm-0', title: 'Logout', :method => :delete) %>
    </span>
      <% else %>
    </ul>

    <span class="navbar-text">
      <%= link_to 'Sign in', "/users/sign_in", class: "my-2 my-sm-0" %>&nbsp;&nbsp;
    </span>

    <span class="navbar-text">
      <%= link_to 'Sign Up', "/users/sign_up", class: "btn btn-outline-dark my-2 my-sm-0" %>
    </span>
      <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Miniapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render '/layouts/nav' %>
    <div class="container-fluid">
      <%= yield %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
      <footer></footer>
  </div> <!-- /container -->
</body>
</html>

app/views/lists/_form.html.erb
<%= form_with model: @list, class: 'ls-form ls-form-horizontal row', local: true do |f| %>
  <div class = 'ls-label col-md-12'>
    <p>
      <%= f.label :name %>
      <%= f.text_field :name, placeholder: 'Nome da Lista'  %>
    </p>
    <p>
      <%= f.label :description %>
      <%= f.text_field :description, placeholder: 'Algum detalhes sobre a tarefa..'  %>
    </p>
        <p>
        <%= f.label :status %>
        <%= f.select :status, List.statuses.map { |key, value| [key.humanize, key] } %>
    </p>
    <p>
      <%= f.fields_for :tasks do |f| %>
        <%= render 'task_fields', f: f %>
      <% end %>
      <%= link_to_add_fields "Nova Tarefa", f, :tasks %>
    </p>
  </div>
  <div class="button">
    <div class='ls-actions-btn button'>
        <%= f.submit 'Salvar', class: 'ls-btn', style: "color: rgb(79, 89, 216);" %>
        <%= link_to 'Voltar', url_for(:back), class:"ls-btn" %>
    </div>
  </div>
<% end %>

<script>

$('form').on('click', '.remove-fields', function(event) {
  console.log('clicked')
  $(this).prev('input[type=hidden]').val('1');
  $(this).closest('fieldset').hide();
  return event.preventDefault();
  });

$('form').on('click', '.add_fields', function(event) {
  console.log('clicked!')
  var regexp, time;
  time = new Date().getTime();
  regexp = new RegExp($(this).data('id'), 'g');
  $(this).before($(this).data('fields').replace(regexp, time));
  return event.preventDefault();
});


</script>

app/views/lists/_task_fields.html.erb
<fieldset>
    <p>
      <%= f.label :title %>
      <%= f.text_field :title, placeholder: 'Descreva a tarefa'  %>
      <%= link_to "remove", '#', class: "remove_fields" %>
    </p>
</fieldset>

app/views/lists/favorite.html.erb
<tbody>
  <% @current_user.favorites.each do |favorite| %>
      <tr id="favorite-<%= favorite.id %>">
        <td><%= favorite.list.id %></td>
        <td><%= favorite.list.name %></td>
  <% end %>
</tbody>

app/views/lists/index.html.erb
<p id="notice"><%= notice %></p>
<%= link_to 'Nova Lista', new_list_path, class: "btn btn-primary" %>
<hr>
<%= tag.div id: :boards, data: { lists: @lists.to_json(include: :tasks) } %>

app/views/lists/new.html.erb
<h1> Nova Tarefa </h1>



<%= render partial: 'form', locals: { customer: @list } %> 

app/views/lists/show.html.erb
<%= @list.id %>
<%= @list.name %>
<%= @list.status %>
<%= @list.description %>
<% @list.tasks.each do |task| %>
<%= task.title %>
<%= link_to favorite_text, favorites_update_path(list: @list), id:
        'favorite_link', remote: true %>
<% end %>